// Code generated by MockGen. DO NOT EDIT.
// Source: internal/generator/workout_generator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "heavybagworkout/internal/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockcombosForWorkPeriodGenerator is a mock of combosForWorkPeriodGenerator interface.
type MockcombosForWorkPeriodGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockcombosForWorkPeriodGeneratorMockRecorder
}

// MockcombosForWorkPeriodGeneratorMockRecorder is the mock recorder for MockcombosForWorkPeriodGenerator.
type MockcombosForWorkPeriodGeneratorMockRecorder struct {
	mock *MockcombosForWorkPeriodGenerator
}

// NewMockcombosForWorkPeriodGenerator creates a new mock instance.
func NewMockcombosForWorkPeriodGenerator(ctrl *gomock.Controller) *MockcombosForWorkPeriodGenerator {
	mock := &MockcombosForWorkPeriodGenerator{ctrl: ctrl}
	mock.recorder = &MockcombosForWorkPeriodGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcombosForWorkPeriodGenerator) EXPECT() *MockcombosForWorkPeriodGeneratorMockRecorder {
	return m.recorder
}

// GenerateCombosForWorkPeriod mocks base method.
func (m *MockcombosForWorkPeriodGenerator) GenerateCombosForWorkPeriod(roundNumber, totalRounds int, workDuration time.Duration, pattern models.WorkoutPattern, previousMoveCount *int) models.Combo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCombosForWorkPeriod", roundNumber, totalRounds, workDuration, pattern, previousMoveCount)
	ret0, _ := ret[0].(models.Combo)
	return ret0
}

// GenerateCombosForWorkPeriod indicates an expected call of GenerateCombosForWorkPeriod.
func (mr *MockcombosForWorkPeriodGeneratorMockRecorder) GenerateCombosForWorkPeriod(roundNumber, totalRounds, workDuration, pattern, previousMoveCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCombosForWorkPeriod", reflect.TypeOf((*MockcombosForWorkPeriodGenerator)(nil).GenerateCombosForWorkPeriod), roundNumber, totalRounds, workDuration, pattern, previousMoveCount)
}
