// Code generated by MockGen. DO NOT EDIT.
// Source: heavybagworkout/internal/timer (interfaces: TimerDisplayHandler)

// Package mocks is a generated GoMock package.
package mocks

import (
	types "heavybagworkout/internal/types"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTimerDisplayHandler is a mock of TimerDisplayHandler interface.
type MockTimerDisplayHandler struct {
	ctrl     *gomock.Controller
	recorder *MockTimerDisplayHandlerMockRecorder
}

// MockTimerDisplayHandlerMockRecorder is the mock recorder for MockTimerDisplayHandler.
type MockTimerDisplayHandlerMockRecorder struct {
	mock *MockTimerDisplayHandler
}

// NewMockTimerDisplayHandler creates a new mock instance.
func NewMockTimerDisplayHandler(ctrl *gomock.Controller) *MockTimerDisplayHandler {
	mock := &MockTimerDisplayHandler{ctrl: ctrl}
	mock.recorder = &MockTimerDisplayHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimerDisplayHandler) EXPECT() *MockTimerDisplayHandlerMockRecorder {
	return m.recorder
}

// OnPeriodEnd mocks base method.
func (m *MockTimerDisplayHandler) OnPeriodEnd(arg0 types.PeriodType, arg1 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnPeriodEnd", arg0, arg1)
}

// OnPeriodEnd indicates an expected call of OnPeriodEnd.
func (mr *MockTimerDisplayHandlerMockRecorder) OnPeriodEnd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPeriodEnd", reflect.TypeOf((*MockTimerDisplayHandler)(nil).OnPeriodEnd), arg0, arg1)
}

// OnPeriodStart mocks base method.
func (m *MockTimerDisplayHandler) OnPeriodStart(arg0 types.PeriodType, arg1 int, arg2 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnPeriodStart", arg0, arg1, arg2)
}

// OnPeriodStart indicates an expected call of OnPeriodStart.
func (mr *MockTimerDisplayHandlerMockRecorder) OnPeriodStart(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPeriodStart", reflect.TypeOf((*MockTimerDisplayHandler)(nil).OnPeriodStart), arg0, arg1, arg2)
}

// OnTimerUpdate mocks base method.
func (m *MockTimerDisplayHandler) OnTimerUpdate(arg0 time.Duration, arg1 types.PeriodType, arg2 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnTimerUpdate", arg0, arg1, arg2)
}

// OnTimerUpdate indicates an expected call of OnTimerUpdate.
func (mr *MockTimerDisplayHandlerMockRecorder) OnTimerUpdate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnTimerUpdate", reflect.TypeOf((*MockTimerDisplayHandler)(nil).OnTimerUpdate), arg0, arg1, arg2)
}

// OnWorkoutComplete mocks base method.
func (m *MockTimerDisplayHandler) OnWorkoutComplete() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnWorkoutComplete")
}

// OnWorkoutComplete indicates an expected call of OnWorkoutComplete.
func (mr *MockTimerDisplayHandlerMockRecorder) OnWorkoutComplete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnWorkoutComplete", reflect.TypeOf((*MockTimerDisplayHandler)(nil).OnWorkoutComplete))
}

// OnWorkoutStart mocks base method.
func (m *MockTimerDisplayHandler) OnWorkoutStart(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnWorkoutStart", arg0)
}

// OnWorkoutStart indicates an expected call of OnWorkoutStart.
func (mr *MockTimerDisplayHandlerMockRecorder) OnWorkoutStart(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnWorkoutStart", reflect.TypeOf((*MockTimerDisplayHandler)(nil).OnWorkoutStart), arg0)
}
