// Code generated by MockGen. DO NOT EDIT.
// Source: heavybagworkout/internal/timer (interfaces: AudioCueHandler)

// Package mocks is a generated GoMock package.
package mocks

import (
	models "heavybagworkout/internal/models"
	types "heavybagworkout/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAudioCueHandler is a mock of AudioCueHandler interface.
type MockAudioCueHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAudioCueHandlerMockRecorder
}

// MockAudioCueHandlerMockRecorder is the mock recorder for MockAudioCueHandler.
type MockAudioCueHandlerMockRecorder struct {
	mock *MockAudioCueHandler
}

// NewMockAudioCueHandler creates a new mock instance.
func NewMockAudioCueHandler(ctrl *gomock.Controller) *MockAudioCueHandler {
	mock := &MockAudioCueHandler{ctrl: ctrl}
	mock.recorder = &MockAudioCueHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudioCueHandler) EXPECT() *MockAudioCueHandlerMockRecorder {
	return m.recorder
}

// PlayBeep mocks base method.
func (m *MockAudioCueHandler) PlayBeep() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayBeep")
}

// PlayBeep indicates an expected call of PlayBeep.
func (mr *MockAudioCueHandlerMockRecorder) PlayBeep() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayBeep", reflect.TypeOf((*MockAudioCueHandler)(nil).PlayBeep))
}

// PlayComboCallout mocks base method.
func (m *MockAudioCueHandler) PlayComboCallout(arg0 models.Combo, arg1 models.Stance) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayComboCallout", arg0, arg1)
}

// PlayComboCallout indicates an expected call of PlayComboCallout.
func (mr *MockAudioCueHandlerMockRecorder) PlayComboCallout(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayComboCallout", reflect.TypeOf((*MockAudioCueHandler)(nil).PlayComboCallout), arg0, arg1)
}

// PlayPeriodTransition mocks base method.
func (m *MockAudioCueHandler) PlayPeriodTransition(arg0 types.PeriodType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayPeriodTransition", arg0)
}

// PlayPeriodTransition indicates an expected call of PlayPeriodTransition.
func (mr *MockAudioCueHandlerMockRecorder) PlayPeriodTransition(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayPeriodTransition", reflect.TypeOf((*MockAudioCueHandler)(nil).PlayPeriodTransition), arg0)
}

// PlayWorkoutComplete mocks base method.
func (m *MockAudioCueHandler) PlayWorkoutComplete() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayWorkoutComplete")
}

// PlayWorkoutComplete indicates an expected call of PlayWorkoutComplete.
func (mr *MockAudioCueHandlerMockRecorder) PlayWorkoutComplete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayWorkoutComplete", reflect.TypeOf((*MockAudioCueHandler)(nil).PlayWorkoutComplete))
}

// PlayWorkoutStart mocks base method.
func (m *MockAudioCueHandler) PlayWorkoutStart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayWorkoutStart")
}

// PlayWorkoutStart indicates an expected call of PlayWorkoutStart.
func (mr *MockAudioCueHandlerMockRecorder) PlayWorkoutStart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayWorkoutStart", reflect.TypeOf((*MockAudioCueHandler)(nil).PlayWorkoutStart))
}
