// Code generated by MockGen. DO NOT EDIT.
// Source: heavybagworkout/internal/timer (interfaces: AudioCueHandler)

// Package mocks is a generated GoMock package.
package mocks

import (
	models "heavybagworkout/internal/models"
	types "heavybagworkout/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAudioCueHandler is a mock of AudioCueHandler interface.
type MockAudioCueHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAudioCueHandlerMockRecorder
}

// MockAudioCueHandlerMockRecorder is the mock recorder for MockAudioCueHandler.
type MockAudioCueHandlerMockRecorder struct {
	mock *MockAudioCueHandler
}

// NewMockAudioCueHandler creates a new mock instance.
func NewMockAudioCueHandler(ctrl *gomock.Controller) *MockAudioCueHandler {
	mock := &MockAudioCueHandler{ctrl: ctrl}
	mock.recorder = &MockAudioCueHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudioCueHandler) EXPECT() *MockAudioCueHandlerMockRecorder {
	return m.recorder
}

// PlayBeep mocks base method.
func (m *MockAudioCueHandler) PlayBeep() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayBeep")
}

// PlayBeep indicates an expected call of PlayBeep.
func (mr *MockAudioCueHandlerMockRecorder) PlayBeep() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayBeep", reflect.TypeOf((*MockAudioCueHandler)(nil).PlayBeep))
}

// PlayComboCallout mocks base method.
func (m *MockAudioCueHandler) PlayComboCallout(combo models.Combo, stance models.Stance) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayComboCallout", combo, stance)
}

// PlayComboCallout indicates an expected call of PlayComboCallout.
func (mr *MockAudioCueHandlerMockRecorder) PlayComboCallout(combo, stance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayComboCallout", reflect.TypeOf((*MockAudioCueHandler)(nil).PlayComboCallout), combo, stance)
}

// PlayPeriodTransition mocks base method.
func (m *MockAudioCueHandler) PlayPeriodTransition(periodType types.PeriodType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayPeriodTransition", periodType)
}

// PlayPeriodTransition indicates an expected call of PlayPeriodTransition.
func (mr *MockAudioCueHandlerMockRecorder) PlayPeriodTransition(periodType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayPeriodTransition", reflect.TypeOf((*MockAudioCueHandler)(nil).PlayPeriodTransition), periodType)
}

// PlayRoundCallout mocks base method.
func (m *MockAudioCueHandler) PlayRoundCallout(roundNumber, totalRounds int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayRoundCallout", roundNumber, totalRounds)
}

// PlayRoundCallout indicates an expected call of PlayRoundCallout.
func (mr *MockAudioCueHandlerMockRecorder) PlayRoundCallout(roundNumber, totalRounds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayRoundCallout", reflect.TypeOf((*MockAudioCueHandler)(nil).PlayRoundCallout), roundNumber, totalRounds)
}

// PlayWorkoutComplete mocks base method.
func (m *MockAudioCueHandler) PlayWorkoutComplete() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayWorkoutComplete")
}

// PlayWorkoutComplete indicates an expected call of PlayWorkoutComplete.
func (mr *MockAudioCueHandlerMockRecorder) PlayWorkoutComplete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayWorkoutComplete", reflect.TypeOf((*MockAudioCueHandler)(nil).PlayWorkoutComplete))
}

// PlayWorkoutStart mocks base method.
func (m *MockAudioCueHandler) PlayWorkoutStart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayWorkoutStart")
}

// PlayWorkoutStart indicates an expected call of PlayWorkoutStart.
func (mr *MockAudioCueHandlerMockRecorder) PlayWorkoutStart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayWorkoutStart", reflect.TypeOf((*MockAudioCueHandler)(nil).PlayWorkoutStart))
}

// Stop mocks base method.
func (m *MockAudioCueHandler) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockAudioCueHandlerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAudioCueHandler)(nil).Stop))
}
